@echo off
title Deed Reader Pro - Project Cleanup
color 0C

echo ============================================
echo     DEED READER PRO - PROJECT CLEANUP
echo ============================================
echo.
echo [WARNING] This will delete build artifacts and dependencies!
echo.
echo Files to be deleted:
echo   - deed-reader-web/frontend/node_modules/
echo   - deed-reader-web/backend/venv/
echo   - deed-reader-web/frontend/build/
echo   - Python __pycache__ directories
echo   - Temporary upload files
echo.
echo These can be regenerated by running RUN_APP.bat
echo.
echo Are you sure you want to continue? (Y/N)
choice /C YN /M "Your choice"
if errorlevel 2 goto :cancel

echo.
echo [1/5] Removing frontend dependencies...
if exist "..\deed-reader-web\frontend\node_modules" (
    echo Deleting node_modules... (this may take a while)
    rmdir /s /q "..\deed-reader-web\frontend\node_modules"
    if errorlevel 1 (
        echo [WARNING] Some files couldn't be deleted (may be in use)
    ) else (
        echo [OK] Frontend dependencies removed!
    )
) else (
    echo [OK] node_modules not found (already clean)
)

echo.
echo [2/5] Removing backend virtual environment...
if exist "..\deed-reader-web\backend\venv" (
    echo Deleting venv...
    rmdir /s /q "..\deed-reader-web\backend\venv"
    if errorlevel 1 (
        echo [WARNING] Some files couldn't be deleted (may be in use)
    ) else (
        echo [OK] Backend venv removed!
    )
) else (
    echo [OK] venv not found (already clean)
)

echo.
echo [3/5] Removing build artifacts...
if exist "..\deed-reader-web\frontend\build" (
    echo Deleting build directory...
    rmdir /s /q "..\deed-reader-web\frontend\build"
    echo [OK] Build artifacts removed!
) else (
    echo [OK] Build directory not found
)

echo.
echo [4/5] Cleaning Python cache...
for /d /r "..\deed-reader-web\backend" %%i in (__pycache__) do (
    if exist "%%i" (
        echo Removing %%i
        rmdir /s /q "%%i"
    )
)
echo [OK] Python cache cleaned!

echo.
echo [5/5] Cleaning temporary uploads...
if exist "..\deed-reader-web\backend\uploads\*.pdf" (
    del /q "..\deed-reader-web\backend\uploads\*.pdf"
    echo [OK] PDF uploads cleaned!
)
if exist "..\deed-reader-web\backend\uploads\*.png" (
    del /q "..\deed-reader-web\backend\uploads\*.png"
    echo [OK] Image uploads cleaned!
)

echo.
echo ============================================
echo     CLEANUP COMPLETE!
echo ============================================
echo.
echo Space freed: Potentially 500MB-1GB+
echo.
echo To restore everything, simply run:
echo   scripts\RUN_APP.bat
echo.
echo The app will automatically reinstall all dependencies.
echo.
goto :end

:cancel
echo.
echo [CANCELLED] No files were deleted.
echo.

:end
pause